### ISSUE TITLE
Add SwiftPM support

### ISSUE THREAD

**Issue by mdiep** [PersistX/PersistDB#3]

**Comment by sharplet** [comment]
👋 

I'm keen to help out with this! I think most of these projects will be pretty straightforward to set up with swiftpm. The main thing I have a question about so far is https://github.com/PersistX/Standards. There's no ability to run arbitrary scripts as part of a swiftpm build, so depending on the use cases for that repo we might need to investigate other approaches for sharing. I imagine swiftpm supports submodules, so perhaps that's something to try out? If you have any insight on how the various scripts there might be used in a swiftpm world I'd love to hear.

**Comment by mdiep** [comment]
Awesome! 🎉 

PersistX/Standards doesn't add anything functionally, so it's definitely not required for SwiftPM support. It's just SwiftFormat and SwiftLint.

I do hope to add a CI test in PersistX/Standards that checks that there are no SwiftFormat and SwiftLint changes. But even that wouldn't need to run with SwiftPM.

In fact, now that I think of it, PersistX/Standards _should_ be ignored with SwiftPM—it's also ignored with Carthage builds. It's only meant for development of PersistDB, not for the consumption of it.
